### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by doe300** [doe300/cpptest-lite#1]
- [x] reorder `-Wall -W[..] -Wextra` so exclusions are handled correctly for clang
- [x] fix Clang compilation error. 
  - either by updting clang to a version where it works 
  - or by rewriting the erronous test-case/assertion
- [x] add assertion for string-equals. 
  - support string<->string, string<->char_, char_<->string and char_<->char_
  - print both strngs on failure. Bette yet, print only differentiating parts (similar to JUnit)
- [x] when done, release 0.5
- [x] use version 0.5 with new string-comparison in OHMComm
