### ISSUE TITLE
Roadmap 0.7

### ISSUE THREAD

**Issue by doe300** [doe300/cpptest-lite#5]
- [x] Rewrite comparisons to be easily extensible and allow such things as `NaN == NaN`
  - move into own header
  - write type-specific comparators (similar to output in `formats.h`)
  - always fall back to `==` operator
- [x] Add output for arbitrary types via the `<<` operator
- [x] remove Windows-specific code (e.g. mutices)
- [x] update version in `cpptest.h`
- [x] update branch stable
